Blog_website/urls.py
from django.contrib import admin,sitemaps
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.conf.urls.static import static
from blog.views import *
from base.views import *
from .sitemap import PostSitemap,CategorySitemap
from . import settings

sitemaps = {'category':CategorySitemap,'post':PostSitemap}

urlpatterns = [
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),

    # urls from base.views
    path('robots.txt',robots_txt,name='robots_txt'),
    path('',home, name='home'),    
    path('about/', about,name='about'),
    path('contact/', contact,name='contact'),


    #urls from blog.views
    path('search/', search, name='search'),
    path('<slug:category_slug>/<slug:slug>/', details, name='post_details'),
    path('<slug:slug>/', category, name='category_details'),
   
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from datetime import datetime

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    contact_date = models.DateTimeField(auto_now_add=True, )

    

    def __str__(self):
        return self.name

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.\
choices = (
    ("Draft","Draft"),
    ("Published","Published"),
    ('Archived','Archived'),
)

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug=models.SlugField()

    class Meta:
        ordering =('title',)
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return '/%s' % self.slug
    
    
class Post(models.Model):
    category=models.ForeignKey(Category,related_name='posts',on_delete=models.CASCADE)
    title= models.CharField(max_length=255)
    intro = models.TextField(max_length=500)
    slug = models.SlugField()
    image = models.ImageField(upload_to="media", blank=True)
    body = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=choices, max_length=255)
    views = models.IntegerField(default=0)

    class Meta:
        ordering = ('-publish_date',)
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return '/%s/%s' % (self.category.slug,self.slug)



class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)
        
    def __str__(self):
        return self.name

base/forms.py
from django import forms

from .models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject','body' )

blog/forms.py
from django import forms

from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'comment', )

base/views.py
from django.shortcuts import *
from blog.models import *
from .forms import *

# Create your views here.    prepopulated_fields = {'slug':('title',)}

def home(request):
    posts = Post.objects.filter(status="Published")
    local = {
        "posts": posts
    }
    return render(request,'base/index.html', local)

def about(request):
    return render(request,'base/about.html')

def contact(request): 
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact' , )
    else:
        form = ContactForm()
     
    #comments = post.comments.all()  # Retrieve all comments for this post
    
    
    return render(request,'base/contact.html',{'form':form})

blog/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404,redirect
from .models import *
from .forms import *
# Create your views here.

def details(request, category_slug,slug):
    post = get_object_or_404(Post, slug=slug,status="Published")
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect('post_details',category_slug=category_slug, slug=slug)
    else:
        form = CommentForm()
    
    #comments = post.comments.all()  # Retrieve all comments for this post
    
    return render(request, 'blog/post.html', {'post': post, 'form': form, })

def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.filter(status="Published")


    return render(request,"blog/category.html",{'category': category, 'posts': posts})

def search(request):
    query = request.GET.get('query','')

    post = Post.objects.filter(status="Published").filter(Q(title__icontains=query) | Q(intro__icontains=query)| Q(body__icontains=query) )

    return render(request, 'blog/search.html',{'post':post,'query':query})

def robots_txt(request):
    """prevent bots from accessing the admin"""
    text = [
        "User-Agent:*",
        "Disallow: /admin/",
    ]
    return HttpResponse("\n".join(text),content_type='text/plain')

base/templates/base/about.html
{% extends "base/base.html" %}
{% block title %}About{% endblock title %}
{% block body %}
<section class="" title="About" >
    <div class="mt-5 p-3">
        <!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">About us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">We provide all the important news that you may want to know about boxing as a sport and a hobby.</p>

    

</section>
<!--Section: Contact v.2-->
    </div>
</section>
{% endblock body %}

base/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static "images/1200px-Boxing_gloves_icon.svg.png" %}" type="image/png">
    <link rel="icon" href="{% static "images/1200px-Boxing_gloves_icon.svg.png" %}" sizes="32x32" type="image/png">

    <!-- Bootstrap CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% comment %} <link href="{% static "css/fontawsome.css" %}" rel="stylesheet"> {% endcomment %}

    <title>{% block title %}{% endblock title %} | Blog Website</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning fixned-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{% static "images/1200px-Boxing_gloves_icon.svg.png" %}" alt="" width="30" height="24">
          <strong>Blog Website</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            </li>
            
            
          </ul>
          <form class="d-flex" method='get' action="{% url "search" %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
            
          </form>
          <ul class="navbar-nav navbar-end mb-2 mb-lg-0">
            <li class="nav-item">
              
              <a class="nav-link active" href="{% url "about" %}"> About</a>
              
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url "contact" %}"> Contact</a>
              
            </li>
            
            
            
          </ul>
        </div>
      </div>
    </nav>
    {% comment %} <div class="mx- ms-2 me-2"> {% endcomment %}

      {% block body %}{% endblock body %}
    {% comment %} </div> {% endcomment %}
    {% include "base/footer.html" %}
    
            
      

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static "js/bootstrap.js" %}" ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

base/templates/base/contact.html
{% extends "base/base.html" %}
{% block title %}About{% endblock title %}
{% block body %}
<section class="" title="About" >
    <div class="mt-5 p-3">
        <!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5 ">
            <form  method="post" class="form-control">
                {% csrf_token %}
                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="id_name" class="form-label">Name:</label>
                            <input type="text" name="name" maxlength="255" required id="id_name"class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="id_email" class="form-label">Email:</label>
                            <input type="email" name="email" maxlength="255" required id="id_email" class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <label for="id_subject" class="form-label">Subject:</label>
                            <input type="text" name="subject" maxlength="255" required id="id_subject" class="form-control">
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <label for="id_body" class="form-label">Body:</label>
                            <textarea name="body"  rows="5" required id="id_body" class="form-control">
                        </textarea>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

                <div class="text-end text-md-left md-form form-label mt-1">
                    <button type="submit" class="btn btn-success w-50 ">Submit</button>
                </div>
                    
                    
            </form>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Nairobi, Kenya</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+254 113626774</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>lijanleejern11@gmail.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->
    </div>
</section>
{% endblock body %}
<!--Grid row-->
<div class="row">

    <!--Grid column-->
    <div class="col-md-6">
        <div class="md-form mb-0">
            <input type="text" id="name" name="name" class="form-control">
            <label for="name" class="">Your name</label>
        </div>
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-6">
        <div class="md-form mb-0">
            <input type="text" id="email" name="email" class="form-control">
            <label for="email" class="">Your email</label>
        </div>
    </div>
    <!--Grid column-->

</div>
<!--Grid row-->

<!--Grid row-->
<div class="row">
    <div class="col-md-12">
        <div class="md-form mb-0">
            <input type="text" id="subject" name="subject" class="form-control">
            <label for="subject" class="">Subject</label>
        </div>
    </div>
</div>
<!--Grid row-->

<!--Grid row-->
<div class="row">

    <!--Grid column-->
    <div class="col-md-12">

        <div class="md-form">
            <textarea type="text" id="message" name="body" rows="2" class="form-control md-textarea"></textarea>
            <label for="message">Your message</label>
        </div>

    </div>
</div>
<!--Grid row-->

<div class="text-center text-md-left">
    <a class="btn btn-primary" type="submit">Send</a>
</div>
<div class="status"></div>

base/templates/base/footer.html
<!-- Footer -->
<footer class="bg-secondary text-center text-white ">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/lijan.leejern" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="www.linkedin.com/in/lijan-leejern-developer" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

    

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
     Copyright &copy 2023:
    <a class="text-white" href="https://mdbootstrap.com/">Created by lijan</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

base/templates/base/index.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block body %}

<section class="mt-2">
    <div class="container mx-3"> <!-- Added mx-3 class here for horizontal margin -->
        <div class="row">
            <div class="col-md offset- mx-auto"> <!-- Added mx-auto class for centering content -->
                {% for post in  posts%}                  
                <a class="nav-link text-dark" aria-current="page" href="{% url "post_details" post.category.slug post.slug %}">
                  {% if post.image %}
                    <div class="row bg-light position-relative">
                      <div class="col-md-6 mb-md-0 p-md-1">
                        <img src="{{ post.image.url }}" class="w-75" alt="...">
                      </div>
                      <div class="col-md-6 p-4 ps-md-0">
                        <h5 class="mt-0">{{ post.title }}</h5>
                        <p>{{ post.intro }}</p>
                        <p class="text-primary">read more </p>
                        <h2 class="small text-end text-muted align-self-end">{{ post.publish_date| timesince }} ago</h2>
                      </div>
                    </div>
                  {% else %}
                  <div class="row g-0 bg-light position-relative">
                    
                    <div class="col-md-12 p-4 ps-md-0">
                      <h5 class="mt-0">{{ post.title }}</h5>
                      <p>{{ post.intro }}</p>
                      <h2 class="small text-end text-muted">{{ post.publish_date| timesince }} ago</h2>

                      
                    </div>
                  </div>
                    
                  {% endif%}
                  
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock body %}

blog/templates/blog/category.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}{{ category.title }}{% endblock title %}
{% block body %}

<section class="mt-5">
    <div class="containelr mx-1"> <!-- Added mx-3 class here for horizontal margin -->
        <div class="row">
            <div class="col-lg-8 offset- mx-auto"> <!-- Added mx-auto class for centering content -->
                {% for post in  posts%}                  
                <a class="nav-link text-dark" aria-current="page" href="{% url "post_details" post.category.slug post.slug %}">
                    <div class="content-body border-bottom mb-2">
                      <h1 class="title ">{{ post.title }}</h1>
                      <p> {{ post.intro }}</p>
                      <div class="row">
                        <div class="col">
                            <h2 class="small text-start text-muted">{{ post.views }} views</h2>
                        </div>
                        <div class="col">
                          {% if post.comments.count == 0 %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comments</h2>
                          {% elif post.comments.count == 1 %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comment</h2>
                          {% else %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comments</h2>
                          {% endif %}
                        </div>
                        <div class="col">
                            <h2 class="small text-end text-muted">{{ post.publish_date| timesince }} ago</h2>
                        </div>
                    </div>
                </a>
                {% empty %}
                  <div class="content">
                    <p><strong>There is no posts available.</strong></p>
                  </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock body %}

blog/templates/blog/post.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock title %}
{% block body %}
  <section class="mt-1">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 border-end">
          <div class="content-body">
            <h1 class="title">{{ post.title }}</h1>
            <div class="d-flex justify-content-between">
              <h2 class="small text-muted">{{ post.publish_date|timesince }} ago</h2>
              <span class="text-muted">{{ post.comments.count }} {% if post.comments.count == 1 %}comment{% else %}comments{% endif %}</span>
            </div>
            <p class="card-body"><strong>{{ post.intro }}</strong></p>
            <p>{{ post.body }}</p>
            {% if post.image %}
              <div class="mt-4">
                <img class="img-fluid rounded" src="{{ post.image.url }}" alt="Post Image">
              </div>
            {% endif %}
            <p><small>categories: <a class="link-warning text-success" href={% url "category_details" post.category.slug %}> {{ post.category }}</a></small></p>

            <hr>

            <div class="card">
              <div class="card-body p-4">
                <h5>Add a comment</h5>
                <form method="post">
                  {% csrf_token %}
                  <div class="mb-3">
                    <input class="form-control" type="text" name="name" maxlength="255" placeholder="John Doe" required>
                  </div>
                  <div class="mb-3">
                    <input class="form-control" type="email" name="email" maxlength="255" placeholder="johndoe@gmail.com" required>
                  </div>
                  <div class="mb-3">
                    <textarea class="form-control" name="comment" cols="40" rows="5" required placeholder="Comment here..."></textarea>
                  </div>
                  <div class="text-end">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4 mt-4 mt-lg-0">
          <div class="border-start ps-1">
            <h1 class="page-header mb-4">Comments</h1>
            <div class="comment scrollable-div">
              {% for comment in post.comments.all %}
                <div class="card mb-3 border-round">
                  <div class="row small border-bottom">
                    <div class="col">
                      <strong>{{ comment.name }}</strong>
                    </div>
                    <div class="col text-end">
                      {{ comment.comment_date|timesince }}
                    </div>
                  </div>
                  <p class="text">{{ comment.comment }}</p>
                </div>
              {% empty %}
                <p>No comments for this post.</p>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock body %}

{% comment %} {% extends "base/base.html" %}
{% load static %}
{% block title %}{{  post.title }}{% endblock title %}
{% block body %}
  <section class="">
    <div class=" mt-5">
      <div class=" me-1">
        
          <div class="row">
            <div class="col-lg d-flex border-end">              
              <div class="content-body ">
                <div class="row ">
                  <div class="col-md-6 mt-3">
                    <div class="row">
                      <div class="col">
                          <h1 class="title ">{{ post.title }}</h1>
                      </div>
                      <div class="col">
                          <h2 class="small text-end text-muted">{{ post.publish_date| timesince }} ago</h2>
                      </div>
                    </div>
                    <p class="card-body"> <strong>{{ post.intro }}</strong></p>
                    <p>{{ post.body }}</p>
                  </div>
                  <div class="col mt-3">
                    {% if post.image %}
                      <img class="img-fluid rounded max-width: 100%;" src="{{post.image.url}}"  alt="img">
                    {% else %}
                      <img class="img-responsive" alt="img">
                    {% endif %}
                  </div>
                </div>
                  <hr>
                  
                  <div class="card">
                    <div class="card-body p-4">
                      <div class="d-flex flex-start w-100">
                        
                        <div class="w-100">
                          <h5>Add a comment</h5>
                          <form method="post">
                            {% csrf_token %}
                            <div class="form">
                              <input  class="form-control mb-2" type="text" name="name" maxlength="255" placeholder="John Doe" required id="id_name">
                              <input class="form-control mb-2" type="email" name="email" maxlength="255" required placeholder="johndoe@gmail.com" id="id_email">
                              <textarea class="form-control mb-2" name="comment" cols="40" rows="5" required placeholder="Comment here..."id="id_comment"></textarea>
        
                            </div>
                            <div class="field-body">
                              <div class="text-end">
                                <button type="submit" class="btn btn-success w-50">Submit</button>
                              </div>
                            </div>
                          </form>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                  <!--  -->
                </div>
              
            </div>
            <div class="col-sm-3 " >
              <h1 class="page-header border-bottom">Comments</h1>
              <div class="text-end">
                {% if post.comments.count == 0 %}
                  <label class="text-muted small">{{ post.comments.count }} comments</label>
                {% elif post.comments.count == 1 %}
                  <label class="text-muted small">{{ post.comments.count }} comment</label>
                {% else %}
                <label class="text-muted small">{{ post.comments.count }} comments</label>
                {% endif %}
                
              </div>
              <div class=" comment scrollable-div" >              
                <artical class="media">
                  {% for comment in post.comments.all %}
                    <div class="  card mb-2 p-1 border-round">
                      <div class="row small border-bottom">
                        <div class="col">
                          <strong>{{ comment.name }}</strong>
                        </div>
                        <div class="col text-end">
                          {{ comment.comment_date |timesince}}

                        </div>                    
                      </div>
                      <p class="text">{{ comment.comment }}</p>
                    </div>
                  {% empty %}
                   <p> no comments for this post. </p>
                  {% endfor %}
                </artical>
                
              </div>
            </div>
          </div>
        
      </div>
    </div>
  </section>

{% endblock body %} {% endcomment %}

blog/templates/blog/search.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Search{% endblock title %}
{% block body %}

<section class="mt-5">
    <div class="containelr mx-1"> <!-- Added mx-3 class here for horizontal margin -->
        <div class="row">
            <div class="col-lg-8 offset- mx-auto"> <!-- Added mx-auto class for centering content -->
                <div class="content-body border-bottom mb-2">
                    <h1 class="">Search results</h1>
                    <h3 class="">Query: "{{ query }}"</h3>
                </div>
                {% for post in  post%}                  
                <a class="nav-link text-dark" aria-current="page" href="{% url "post_details" post.category.slug post.slug %}">
                    <div class="content-body border-bottom mb-2">
                      <h1 class="title ">{{ post.title }}</h1>
                      <p> {{ post.intro }}</p>
                      <div class="row">
                        <div class="col">
                            <h2 class="small text-start text-muted">{{ post.views }} views</h2>
                        </div>
                        <div class="col">
                          {% if post.comments.count == 0 %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comments</h2>
                          {% elif post.comments.count == 1 %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comment</h2>
                          {% else %}
                            <h2 class="small text-center text-muted">{{ post.comments.count }} comments</h2>
                          {% endif %}
                        </div>
                        <div class="col">
                            <h2 class="small text-end text-muted">{{ post.publish_date| timesince }} ago</h2>
                        </div>
                    </div>
                </a>
                {% empty %}
                  <div class="content">
                    <p><strong>There is no results available.</strong></p>
                  </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock body %}

 